## Basic Syntax


In [1]:
println("This is used for printing something\nNext line")

This is used for printing something
Next line


In [2]:
my_answer=42
typeof(my_answer)

Int64

In [3]:
my_pi=3.1459
typeof(my_pi)

Float64

In [4]:
😘="kissing pandi"
typeof(😘)
println("Julia allows us to write super generic code, and 😘 is an example of this")

Julia allows us to write super generic code, and 😘 is an example of this


In [5]:
😘=1
😕=-1
🙂=0
println(😕+😘)
println(typeof(😘))
println(😕+😘==🙂)

0
Int64
true


## How to Connect

In [6]:
# You can leave comments on a single line using the pound/hash key

## Syntax for basic maths


In [7]:
sum=3+5

8

In [8]:
difference=10-3

7

In [9]:
multiply=19*5

95

In [10]:
division=67/5

13.4

In [11]:
modulo=101%2

1

In [12]:
power=10^2

100

## Strings

In [13]:
#Enclose your characters in " " or """ """
s1="I am a string"
s2="""I am also a string"""
println(s1,"\n",s2)


I am a string
I am also a string


In [14]:
# Single quotation marks ' ' used to define a character, but NOT a string
typeof('a')

Char

In [15]:
#String Interpolation
name="pandi"
fingures_number=10
toes_number=10
println("Hello,my name is $name.")
println("I have $fingures_number figures and $toes_number toes")

Hello,my name is pandi.
I have 10 figures and 10 toes


In [18]:
#string Concatenation
println(string("first part","second part"))
println(string("first part",10,"number ten")) 
s3="string number one"
s4="string number four"
println(s3*s4)
println("$s3$s4")

first partsecond part
first part10number ten
string number onestring number four
string number onestring number four


## Data Structures
### Dictionaries

In [19]:
phonebook=Dict("Rishi"=>"9391498552","Naveen"=>"7416917907")

Dict{String, String} with 2 entries:
  "Naveen" => "7416917907"
  "Rishi"  => "9391498552"

In [20]:
#Add another entry to dictinary
phonebook["Rishitha"]="9490800141"

"9490800141"

In [21]:
phonebook

Dict{String, String} with 3 entries:
  "Naveen"   => "7416917907"
  "Rishi"    => "9391498552"
  "Rishitha" => "9490800141"

In [23]:
#To delete a key 
pop!(phonebook,"Rishitha")

"9490800141"

In [24]:
#Unlike tuples and arrays , dictinaries are not ordered. So, we can't index into them
phonebook[1]

LoadError: KeyError: key 1 not found

### Tuples

In [25]:
animals=("rat","cat","lion","tiger")

("rat", "cat", "lion", "tiger")

In [26]:
#Indexing starts from one
animals[1]

"rat"

### Arrays


In [27]:
array1=[5,67,23,8745]

4-element Vector{Int64}:
    5
   67
   23
 8745

In [34]:
#In an array the datatype of all elements need not be same

sample=["1",5,8.0,"hiiii"]

4-element Vector{Any}:
  "1"
 5
 8.0
  "hiiii"

In [35]:
sample[1]

"1"

In [36]:
push!(sample,56)


5-element Vector{Any}:
   "1"
  5
  8.0
   "hiiii"
 56

In [37]:
sample


5-element Vector{Any}:
   "1"
  5
  8.0
   "hiiii"
 56

In [38]:
pop!(sample)

56

In [39]:
sample

4-element Vector{Any}:
  "1"
 5
 8.0
  "hiiii"

In [40]:
multidim_array=[["43",78],["hi","hello","bye"]]

2-element Vector{Vector{Any}}:
 ["43", 78]
 ["hi", "hello", "bye"]

In [41]:
rand(4,3)

4×3 Matrix{Float64}:
 0.692493  0.467485   0.0272981
 0.95906   0.0560351  0.170057
 0.274884  0.876482   0.627737
 0.108314  0.0363082  0.00207324

In [42]:
#Creates an array of shape (4,3,2) with random values which ranges from 0-1
rand(4,3,2)

4×3×2 Array{Float64, 3}:
[:, :, 1] =
 0.292243  0.188283  0.498063
 0.749677  0.133198  0.76078
 0.898713  0.303122  0.121423
 0.9496    0.98245   0.254909

[:, :, 2] =
 0.0837376  0.600071   0.863246
 0.22181    0.118085   0.779999
 0.0914293  0.0256075  0.940633
 0.537419   0.595957   0.327099

## LOOPS

In [47]:
n=1
while n<10
    n+=1
    println(n)
end    

2
3
4
5
6
7
8
9
10


In [48]:
for n in 1:10
      println(n)
end    

1
2
3
4
5
6
7
8
9
10


In [49]:
for n= 1:10
     println(n)
end    

1
2
3
4
5
6
7
8
9
10


In [56]:
m,n=5,5
A= zeros(m,n)
A

5×5 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [55]:
for i in 1:m
    for j in 1:n
        A[i,j]=i+j
        
    end
end 
A

5×5 Matrix{Float64}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

In [54]:
#Instead of the above we can use the below syntax 
B=zeros(m,n)
for i in 1:m, j in 1:n
    B[i,j]=i+j
end
B

5×5 Matrix{Float64}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

In [58]:
c=[i+j for i in 1:m, j in 1:n]
display(c)

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

## Conditional statements

In [59]:
x=10
y=4
if x>y
    println("x>y")
elseif y>x
    println("y>x")
else
    println("x=y") 
end    

x>y


In [62]:
#Ternary operator
(x>y) ? x : y
#Above means if x>y then print x else print y

10

In [65]:
#If first condition is true then second condition gets implemented
(x>y) && println("x is greater than y")
(y>x) && println("I don't get printed ")

x is greater than y


false

## Functions

In [66]:
function sayhi(name)
    println("my name is $name")
end   

sayhi (generic function with 1 method)

In [67]:
function f(x)
    x^2
end    

f (generic function with 1 method)

In [68]:
sayhi("Rishi")

my name is Rishi


In [69]:
f(10)

100

In [72]:
#Alternatively we can declare a function in a single line

greeting(name) = println("HI PANDI\n Ummmaa $name")

greeting (generic function with 1 method)

In [73]:
greeting("Naveen")

HI PANDI
 Ummmaa Naveen


In [74]:
#Finally, we could have declared these as "anonymous" functions
sayhi3=name -> println("Hi $name, it's great to see you!")

#5 (generic function with 1 method)

In [75]:
sayhi3("Naveen")

Hi Naveen, it's great to see you!


In [76]:
sayhi3(3456888)

Hi 3456888, it's great to see you!


In [77]:
A=rand(4,2)
sayhi3(A)

Hi [0.26218693814823824 0.14103080876894625; 0.5307004111110671 0.20288408653737133; 0.16700707629341316 0.33357238506494236; 0.8199092687221706 0.46649162459334115], it's great to see you!


In [78]:
#But the functions like x^2 don't work on all 
f(A)

LoadError: DimensionMismatch: A has dimensions (4,2) but B has dimensions (4,2)

### Mutating vs non-mutating functions

In [80]:
#By convention, functions folllowed by ! alter their contents and functions lacking ! do not

v=[3,5,2]
sort(v)
print(v)


[3, 5, 2]

In [81]:
#Above v and sort(v) are not same
sort!(v)
println(v)

[2, 3, 5]


### Broadcasting

In [85]:
A = [i + 3*j for j in 0:2, i in 1:3]
display(A)
f(A)

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

3×3 Matrix{Int64}:
  30   36   42
  66   81   96
 102  126  150

In [86]:
f.(A)

3×3 Matrix{Int64}:
  1   4   9
 16  25  36
 49  64  81

In [87]:
v=[1,2,3]
f(v)


LoadError: MethodError: no method matching ^(::Vector{Int64}, ::Int64)

Closest candidates are:
  ^(::Float16, ::Integer)
   @ Base math.jl:1283
  ^(::Float32, ::Integer)
   @ Base math.jl:1277
  ^(::Regex, ::Integer)
   @ Base regex.jl:863
  ...


In [88]:
f.(v)
#Like it is operation over individual element

3-element Vector{Int64}:
 1
 4
 9